
-- ============================================================
-- Food Ordering Chatbot Database
-- PostgreSQL Version
-- ============================================================

-- Run this script after connecting to:
-- food_ordering_chatbot


-- ============================================================
-- Remove existing objects
-- ============================================================

DROP TABLE IF EXISTS order_tracking CASCADE;
DROP TABLE IF EXISTS orders CASCADE;
DROP TABLE IF EXISTS food_items CASCADE;

DROP FUNCTION IF EXISTS get_price_for_item(VARCHAR);
DROP FUNCTION IF EXISTS get_total_order_price(INTEGER);
DROP PROCEDURE IF EXISTS insert_order_item(VARCHAR, INTEGER, INTEGER);


-- ============================================================
-- Food items table
-- ============================================================

CREATE TABLE food_items (
    item_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL,
    price NUMERIC(10, 2) NOT NULL,

    CONSTRAINT food_items_pkey
        PRIMARY KEY (item_id),

    CONSTRAINT food_items_name_unique
        UNIQUE (name),

    CONSTRAINT food_items_price_positive
        CHECK (price >= 0)
);


-- ============================================================
-- Menu data
-- Prices are example values and can be changed later
-- ============================================================

INSERT INTO food_items (item_id, name, price)
VALUES
    (1,  'Pizza',            8.00),
    (2,  'Burger',           6.00),
    (3,  'Cheeseburger',     7.00),
    (4,  'Chicken Burger',   7.50),
    (5,  'French Fries',     3.00),
    (6,  'Chicken Sandwich', 6.50),
    (7,  'Chicken Nuggets',  5.00),
    (8,  'Hot Dog',          4.50),
    (9,  'Cola',             2.00),
    (10, 'Orange Juice',     3.00),
    (11, 'Water',            1.00),
    (12, 'Milkshake',        4.00);


-- Reset the identity sequence after manually inserting IDs
SELECT setval(
    pg_get_serial_sequence('food_items', 'item_id'),
    (SELECT MAX(item_id) FROM food_items)
);


-- ============================================================
-- Orders table
-- Each row represents one food item within an order
-- ============================================================

CREATE TABLE orders (
    order_id INTEGER NOT NULL,
    item_id INTEGER NOT NULL,
    quantity INTEGER NOT NULL,
    total_price NUMERIC(10, 2) NOT NULL,

    CONSTRAINT orders_pkey
        PRIMARY KEY (order_id, item_id),

    CONSTRAINT orders_item_fk
        FOREIGN KEY (item_id)
        REFERENCES food_items (item_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT orders_quantity_positive
        CHECK (quantity > 0),

    CONSTRAINT orders_total_price_nonnegative
        CHECK (total_price >= 0)
);


-- ============================================================
-- Order tracking table
-- ============================================================

CREATE TABLE order_tracking (
    order_id INTEGER NOT NULL,

    status VARCHAR(50) NOT NULL
        DEFAULT 'pending',

    CONSTRAINT order_tracking_pkey
        PRIMARY KEY (order_id),

    CONSTRAINT order_tracking_status_check
        CHECK (
            status IN (
                'pending',
                'confirmed',
                'preparing',
                'ready',
                'out for delivery',
                'in transit',
                'delivered',
                'cancelled'
            )
        )
);


-- ============================================================
-- Example order data
-- ============================================================

-- Order 40:
-- Two burgers and one pizza

INSERT INTO orders (
    order_id,
    item_id,
    quantity,
    total_price
)
VALUES
    (40, 2, 2, 12.00),
    (40, 1, 1, 8.00);


-- Order 41:
-- Three milkshakes, two chicken burgers and four fries

INSERT INTO orders (
    order_id,
    item_id,
    quantity,
    total_price
)
VALUES
    (41, 12, 3, 12.00),
    (41, 4,  2, 15.00),
    (41, 5,  4, 12.00);


INSERT INTO order_tracking (order_id, status)
VALUES
    (40, 'delivered'),
    (41, 'in transit');


-- ============================================================
-- Function: get_price_for_item
--
-- Returns the price of a food item.
-- Returns -1 when the item does not exist.
--
-- The comparison is case-insensitive:
-- Pizza, pizza and PIZZA will all match.
-- ============================================================

CREATE OR REPLACE FUNCTION get_price_for_item(
    p_item_name VARCHAR
)
RETURNS NUMERIC(10, 2)
LANGUAGE plpgsql
STABLE
AS $$
DECLARE
    v_price NUMERIC(10, 2);
BEGIN
    SELECT price
    INTO v_price
    FROM food_items
    WHERE LOWER(name) = LOWER(TRIM(p_item_name));

    IF NOT FOUND THEN
        RETURN -1;
    END IF;

    RETURN v_price;
END;
$$;


-- ============================================================
-- Function: get_total_order_price
--
-- Returns the total price of an order.
-- Returns -1 when the order does not exist.
-- ============================================================

CREATE OR REPLACE FUNCTION get_total_order_price(
    p_order_id INTEGER
)
RETURNS NUMERIC(10, 2)
LANGUAGE plpgsql
STABLE
AS $$
DECLARE
    v_total_price NUMERIC(10, 2);
BEGIN
    SELECT SUM(total_price)
    INTO v_total_price
    FROM orders
    WHERE order_id = p_order_id;

    IF v_total_price IS NULL THEN
        RETURN -1;
    END IF;

    RETURN v_total_price;
END;
$$;


-- ============================================================
-- Procedure: insert_order_item
--
-- Inserts an item into an order.
--
-- If the same item already exists in the order, its new
-- quantity is added to the existing quantity.
--
-- Example:
-- Existing order contains 2 pizzas.
-- User adds 1 pizza.
-- Final quantity becomes 3 pizzas.
-- ============================================================

CREATE OR REPLACE PROCEDURE insert_order_item(
    p_food_item VARCHAR,
    p_quantity INTEGER,
    p_order_id INTEGER
)
LANGUAGE plpgsql
AS $$
DECLARE
    v_item_id INTEGER;
    v_price NUMERIC(10, 2);
BEGIN
    -- Validate the order ID
    IF p_order_id IS NULL OR p_order_id <= 0 THEN
        RAISE EXCEPTION
            'Invalid order ID: %',
            p_order_id;
    END IF;

    -- Validate the quantity
    IF p_quantity IS NULL OR p_quantity <= 0 THEN
        RAISE EXCEPTION
            'Quantity must be greater than zero. Received: %',
            p_quantity;
    END IF;

    -- Find the requested food item
    SELECT
        item_id,
        price
    INTO
        v_item_id,
        v_price
    FROM food_items
    WHERE LOWER(name) = LOWER(TRIM(p_food_item));

    -- Reject food items that are not on the menu
    IF NOT FOUND THEN
        RAISE EXCEPTION
            'Food item "%" does not exist on the menu.',
            p_food_item;
    END IF;

    -- Insert the new item.
    -- If it already exists, increase its quantity and price.
    INSERT INTO orders (
        order_id,
        item_id,
        quantity,
        total_price
    )
    VALUES (
        p_order_id,
        v_item_id,
        p_quantity,
        v_price * p_quantity
    )
    ON CONFLICT (order_id, item_id)
    DO UPDATE SET
        quantity =
            orders.quantity + EXCLUDED.quantity,

        total_price =
            (orders.quantity + EXCLUDED.quantity) * v_price;
END;
$$;


-- ============================================================
-- Optional helper function: create a new order ID
--
-- Returns the next available order ID.
-- This keeps the tutorial's database structure while avoiding
-- hard-coded IDs in the Python backend.
-- ============================================================

CREATE OR REPLACE FUNCTION get_next_order_id()
RETURNS INTEGER
LANGUAGE sql
VOLATILE
AS $$
    SELECT COALESCE(MAX(order_id), 0) + 1
    FROM (
        SELECT order_id FROM orders

        UNION

        SELECT order_id FROM order_tracking
    ) AS existing_orders;
$$;


-- ============================================================
-- Optional procedure: finalize an order
--
-- Adds the completed order to the tracking table.
-- ============================================================

CREATE OR REPLACE PROCEDURE finalize_order(
    p_order_id INTEGER
)
LANGUAGE plpgsql
AS $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM orders
        WHERE order_id = p_order_id
    ) THEN
        RAISE EXCEPTION
            'Order % does not contain any items.',
            p_order_id;
    END IF;

    INSERT INTO order_tracking (
        order_id,
        status
    )
    VALUES (
        p_order_id,
        'confirmed'
    )
    ON CONFLICT (order_id)
    DO UPDATE SET
        status = EXCLUDED.status;
END;
$$;


-- ============================================================
-- Testing queries
-- These are optional and can be run after database creation.
-- ============================================================

-- Display the menu
SELECT *
FROM food_items
ORDER BY item_id;


-- Get the price of pizza
SELECT get_price_for_item('Pizza');


-- Case-insensitive test
SELECT get_price_for_item('cheeseburger');


-- Total price for order 40
SELECT get_total_order_price(40);


-- Add two pizzas to order 42
CALL insert_order_item(
    'Pizza',
    2,
    42
);


-- Add one burger to order 42
CALL insert_order_item(
    'Burger',
    1,
    42
);


-- Add another pizza.
-- The quantity of pizza becomes 3.
CALL insert_order_item(
    'Pizza',
    1,
    42
);


-- View order 42
SELECT
    o.order_id,
    f.name,
    o.quantity,
    f.price AS unit_price,
    o.total_price
FROM orders AS o
JOIN food_items AS f
    ON f.item_id = o.item_id
WHERE o.order_id = 42
ORDER BY f.name;


-- Get the complete order total
SELECT get_total_order_price(42);


-- Mark the order as confirmed
CALL finalize_order(42);


-- Check the order status
SELECT status
FROM order_tracking
WHERE order_id = 43;
select* from orders;